apiVersion: bruk.airon.ai/v1alpha1
kind: BrukModel
metadata:
  labels:
    app.kubernetes.io/name: airon-operator
    app.kubernetes.io/managed-by: kustomize
  name: brukmodel-sample
spec:
  # TODO(user): Add fields here
